model: "Employee"
title: "Fill Form - Emplyee Creation"
labels: 
  code: "Document Code"
  name: "Document Name"
  file: "Document"
  version_controlled: "Version Controlled?"
fields:
  column1:
    code:
      label:
        size: 3 #between 1-12
      html:
        size: 7 #between 1-12
        tag: "input"
        type: "text"
    email:
      label:
        size: 3 #between 1-12
      html:
        size: 7 #between 1-12
        tag: "input"
        type: "text"
  column2:
    name:
      label:
        size: 3 #between 1-12
      html:
        size: 7 #between 1-12
        tag: "input"
        type: "text"
